# Generated by Django 5.0.4 on 2024-04-13 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pollution', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satiety', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_alive', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=1)),
                ('time_of_birth', models.DateTimeField(auto_now_add=True)),
                ('time_of_sell', models.DateTimeField(blank=True, null=True)),
                ('time_of_breeding', models.DateTimeField(blank=True, null=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium_care.aquarium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satiety', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_alive', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=1)),
                ('time_of_birth', models.DateTimeField(auto_now_add=True)),
                ('time_of_sell', models.DateTimeField(blank=True, null=True)),
                ('time_of_breeding', models.DateTimeField(blank=True, null=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium_care.aquarium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satiety', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_alive', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=1)),
                ('time_of_birth', models.DateTimeField(auto_now_add=True)),
                ('time_of_sell', models.DateTimeField(blank=True, null=True)),
                ('time_of_breeding', models.DateTimeField(blank=True, null=True)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium_care.aquarium')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
