# Generated by Django 5.0.4 on 2024-04-13 12:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fish',
            name='satiety',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 53, 59, 813925)),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='satiety',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 53, 59, 813925)),
        ),
        migrations.AlterField(
            model_name='snail',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snail',
            name='satiety',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 53, 59, 813925)),
        ),
    ]
