# Generated by Django 5.0.4 on 2024-04-13 13:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0002_alter_fish_gender_alter_fish_satiety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquarium',
            name='name',
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='pollution',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 12, 10, 237479)),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 12, 10, 237479)),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 12, 10, 237479)),
        ),
    ]
