# Generated by Django 5.0.4 on 2024-04-13 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0003_remove_aquarium_name_alter_aquarium_pollution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 15, 21, 267310)),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 15, 21, 267310)),
        ),
        migrations.AlterField(
            model_name='snail',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 16, 15, 21, 267310)),
        ),
    ]
