# Generated by Django 5.0.4 on 2024-04-13 14:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0004_alter_fish_gender_alter_fish_time_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fish',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fish',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shrimp',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shrimp',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snail',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snail',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 17, 8, 56, 967078)),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 17, 8, 56, 967078)),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 17, 8, 56, 967078)),
        ),
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
