# Generated by Django 5.0.4 on 2024-04-13 15:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0005_aquarium_owner_fish_cost_fish_is_sold_shrimp_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 18, 21, 35, 854043)),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 18, 21, 35, 854043)),
        ),
        migrations.AlterField(
            model_name='snail',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 18, 21, 35, 854043)),
        ),
        migrations.DeleteModel(
            name='PinCode',
        ),
    ]
