# Generated by Django 5.0.4 on 2024-04-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium_care', '0007_alter_fish_gender_alter_fish_time_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fish',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fish',
            name='time_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fugue',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fugue',
            name='time_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='time_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='snail',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='snail',
            name='time_of_birth',
            field=models.DateTimeField(),
        ),
    ]
